### ISSUE TITLE
[Documentation] Start Documentation and docstrings

### ISSUE THREAD

**Issue by TioMinho** [aaltoKEPO/SystemLevelControl.jl#8]
### Summary

The package is progressing but the documentation is still empty. I'm creating this issue as a both a reminder and tracker for starting the documentation page and to not implement more function without docstrings.

### Tasks

- [ ] Define the `docs/` layout and start populating the pages with some content. Suggestion is for the tabs: Introduction (including Quickstart), Examples, Manual, Contribution Guide, API Reference, Release notes.
- [ ] Define a docstrings style and start documenting all functions. 
- [ ] Upload simple benchmark systems that can be downloaded and used directly through the package (gym style). We can then restrict the tutorials/examples to those systems.
